### PR TITLE
Bugfix and documentation update

### PR DESCRIPTION
**Pull request by simonamor**
Fixed what happens when you use a hashref instead of arrayref in the fixture. Also updated documentation to include example file for use with fixture_path.

### CODE REVIEW

**Comment by colinnewell** [comment]
If you have time a test for the bugfix would be ideal.  Otherwise I'll look at adding one myself when I have a moment.

**Comment by colinnewell** [comment]
Oh, I should add, thanks for the improvements, they are much appreciated.

**Comment by simonamor** [comment]
Test added. I ran the same test against the previous release and the load from hashref failed as expected (only imported data to one of the resultsets at random).

**Comment by colinnewell** [comment]
Perfect thanks.  I'll give it a go and do a release.

**Pull request merged**
